//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class A_png
    {
        public const string BundleName = "a_png";
        public const string A = "a";
    }
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "AssetObj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "AssetObj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "AssetObj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "AssetObj";
    }
    public class B_png
    {
        public const string BundleName = "b_png";
        public const string B = "b";
    }
    public class Ball_prefab
    {
        public const string BundleName = "ball_prefab";
        public const string BALL = "Ball";
    }
    public class Blue_jpg
    {
        public const string BundleName = "blue_jpg";
        public const string QIU_03 = "qiu_03";
    }
    public class Bomb2_png
    {
        public const string BundleName = "bomb2_png";
        public const string BOMB2 = "bomb2";
    }
    public class C_png
    {
        public const string BundleName = "c_png";
        public const string C = "c";
    }
    public class Destroyfx_prefab
    {
        public const string BundleName = "destroyfx_prefab";
        public const string DESTROYFX = "DestroyFX";
    }
    public class Gameoverpanel_prefab
    {
        public const string BundleName = "gameoverpanel_prefab";
        public const string GAMEOVERPANEL = "GameOverPanel";
    }
    public class Gamepanel_prefab
    {
        public const string BundleName = "gamepanel_prefab";
        public const string GAMEPANEL = "GamePanel";
    }
    public class Green_jpg
    {
        public const string BundleName = "green_jpg";
        public const string QIU_02 = "qiu_02";
    }
    public class Imageprefaba_prefab
    {
        public const string BundleName = "imageprefaba_prefab";
        public const string IMAGEPREFABA = "ImagePrefabA";
    }
    public class Imageprefabb_prefab
    {
        public const string BundleName = "imageprefabb_prefab";
        public const string IMAGEPREFABB = "ImagePrefabB";
    }
    public class Imageprefabc_prefab
    {
        public const string BundleName = "imageprefabc_prefab";
        public const string IMAGEPREFABC = "ImagePrefabC";
    }
    public class Levelselectpanel_prefab
    {
        public const string BundleName = "levelselectpanel_prefab";
        public const string LEVELSELECTPANEL = "LevelSelectPanel";
    }
    public class Red_jpg
    {
        public const string BundleName = "red_jpg";
        public const string QIURED = "qiu-red";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "SceneRes";
    }
    public class Shooterposes_asset
    {
        public const string BundleName = "shooterposes_asset";
        public const string SHOOTERPOSES = "ShooterPoses";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Squarea_prefab
    {
        public const string BundleName = "squarea_prefab";
        public const string SQUAREA = "SquareA";
    }
    public class Startgamepanel_prefab
    {
        public const string BundleName = "startgamepanel_prefab";
        public const string STARTGAMEPANEL = "StartGamePanel";
    }
    public class Succpanel_prefab
    {
        public const string BundleName = "succpanel_prefab";
        public const string SUCCPANEL = "SuccPanel";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "TextureExample1";
    }
    public class Uibasicpanel_prefab
    {
        public const string BundleName = "uibasicpanel_prefab";
        public const string UIBASICPANEL = "UIBasicPanel";
    }
    public class Uimultipanel_prefab
    {
        public const string BundleName = "uimultipanel_prefab";
        public const string UIMULTIPANEL = "UIMultiPanel";
    }
    public class Uipanelwithimageprefab_prefab
    {
        public const string BundleName = "uipanelwithimageprefab_prefab";
        public const string UIPANELWITHIMAGEPREFAB = "UIPanelWithImagePrefab";
    }
    public class Uistackpanel1_prefab
    {
        public const string BundleName = "uistackpanel1_prefab";
        public const string UISTACKPANEL1 = "UIStackPanel1";
    }
    public class Uistackpanel2_prefab
    {
        public const string BundleName = "uistackpanel2_prefab";
        public const string UISTACKPANEL2 = "UIStackPanel2";
    }
    public class Worldselectpanel_prefab
    {
        public const string BundleName = "worldselectpanel_prefab";
        public const string WORLDSELECTPANEL = "WorldSelectPanel";
    }
    public class Yellow_jpg
    {
        public const string BundleName = "yellow_jpg";
        public const string QIU_01 = "qiu_01";
    }
}
